org: marcelloromani
app: gen-auto-umiliatori
service: gen-auto-umiliatori

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  gen-text:
    memorySize: 256
    handler: gen_text.handler
    events:
      - http: GET /umiliami
