name: Continuous Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Serverless Deploy
        uses: serverless/github-action@v2.18.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_BOT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_BOT_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        with:
          args: deploy

      - name: Grab API GW endpoint
        uses: serverless/github-action@v2.18.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_BOT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_BOT_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        with:
          entrypoint: /bin/sh
          args: -c "serverless info --verbose | grep ServiceEndpoint | awk '{print $2}' > api-endpoint.txt"

      - name: Show API GW endpoint
        run: cat api-endpoint.txt
